version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins_sonar_network
    environment:
      - SONARQUBE_HOST=http://sonarqube:9000

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins_sonar_network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_MAXACTIVE=60
      - SONARQUBE_JDBC_MAXIDLE=5
      - SONARQUBE_JDBC_MINIDLE=2

  sonarqube_db:
    image: postgres:latest
    container_name: sonarqube_db
    networks:
      - jenkins_sonar_network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

networks:
  jenkins_sonar_network:
    driver: bridge

volumes:
  jenkins_data:
    driver: local
  sonarqube_db_data:
    driver: local
